### ISSUE TITLE
GetRecords handler. Check for the presence

### ISSUE THREAD

**Issue by d1eselboy** [anytypeio/go-threads#5]
**Problem**
Some node, polling other nodes for a new thread, can initiate a resource-intensive search process if some of the nodes do not have this thread yet.

**Solution**
In the server-side handler `GetRecords`, we need to check for the presence of the requested record.
So we should disable rewinding of the entire chain when a requested record has not yet arrived.

**Sub-tasks**
- [x] Implement changes
- [x] Waiting for textile for approve in upstream
- [ ] Update dependency in middleware and move for test
- [ ] Change local repo

**Comment by dgtony** [comment]
Related PR: https://github.com/textileio/go-threads/pull/471
