### ISSUE TITLE
All known devices poll for each thread enhancement

### ISSUE THREAD

**Issue by d1eselboy** [anytypeio/go-threads#7]
**Problem**
Some accounts will have old devices that can be never online again. 
The number of threads is growing and the poll of all devices will grow proportionally. 

**Possible solution**
We can make an adaptive request rate. Based on the persistent sync statuses, we can reduce the polling rate of devices that was seen a long time ago. This way we can keep the complexity of the polls from growing. 

We can do the implementation by peers and by threads, we need to decide which approach is better.

**Sub-tasks**
- [x] Implement `AddrsEdge` in logstore. `till 10.02`
- [ ] Extend internal communication interface of ThreadsDB nodes with a new method `GetThreadEdge`. Do not bump protocol version, as it should work with old nodes as well.
- [ ] Wire new method in all corresponding internal communicating processes.
- [ ] Implement adaptive queue component for requesting records from other nodes.
- [ ] Replace all direct record calls with a request submitting to the adaptive queue and further processing with some calling mechanism.

**Comment by dgtony** [comment]
Further investigation of ThreadsDB reveales some undesirable communication patterns to be eliminated. Specifically, `GetRecords` call is invoked too frequently, producing a lot of traffic and CPU load, especially on a high-degree nodes.

**Optimization plan (draft)**
1. Extend internal communication interface of ThreadsDB nodes with a new method `ThreadChanged`. New method should be cheap in terms of CPU and will be used for the fast-path detecting of thread's modified state.
2. Wire new method in all corresponding internal communicating processes.
3. Implement adaptive queue component for requesting records from other nodes. Such component must combine request deduplication mechanism and dynamic request scheduling based on the rate of requests for the peer.
4. Replace all direct record calls with a request submitting to the adaptive queue and further processing with some calling mechanism.

First iteration won't take into account communication history of the peer (from the sync status storage).

**Comment by dgtony** [comment]
Feature branch: https://github.com/anytypeio/go-threads/tree/improvement/get-thread-edge
